# LLD文件的配置

# fileName支持绝对路径，如只有文件名，则默认在lld_file目录下
;[lld]
;fileName=D:\PycharmProjects\ZTP_config\NTD_cfg_processor\lld_file\lld_cpm_test_ZTP_LLD.xlsx
;sheetName=网络IP规划
;
;[ZTP]
;fileName=D:\PycharmProjects\ZTP_config\NTD_cfg_processor\lld_file\项目信息收集表.xlsx
;sheetName=ZTP配置
;
;# 支持绝对路径，如只有文件名，则默认在template目录下
;[template]
;L1=D:\PycharmProjects\ZTP_config\NTD_cfg_processor\template\Ztp_L1_optical_template.cfg
;L2=D:\PycharmProjects\ZTP_config\NTD_cfg_processor\template\Ztp_L2_optical_template.cfg

# LLD表中用于生成配置的sheet页，必须包含如下内容，不强制要求顺序（兼容乱序）：
# 设备名、设备ESN、管理IP配置、网关、SwitchId、BGP AS号、
# LoopBack IP1、LoopBack IP2、LoopBack IP3、LoopBack IP4、LoopBack IP5、LoopBack IP6、LoopBack IP7 
# 表格中如列名发生变化，直接改这里即可，如“管理IP配置”改成了“管理口IP”等。
[confElements]
deviceName=交换机名称
esn=ESN
methIP=管理面IP
gateway=网关
switchId=交换机ID
level=L1/L2平面
bgpAs=BGP AS号
roomName=机房名称
rackNum=机柜编号
rackLocation=柜内位置
loopback0=loopBack0
loopback1=loopBack1
loopback2=loopBack2
loopback3=loopBack3
loopback4=loopBack4
loopback5=loopBack5
loopback6=loopBack6

# 模板中的替换标记。此处配置个数要与confElements一致。也要与模板中的一致。
[replaceLabel]
deviceName={{DeviceName}}
esn={{esn}}
location = {{DeviceLocaion}}
methIP={{MngIp}}
gateway={{MngIpGateWay}}
subMask={{subMask}}
switchLevel={{switchLevel}}
switchId={{switchId}}
bgpAs={{BGP_AS_NUM}}
loopback0={{LoopBackIp0}}
loopback1={{LoopBackIp1}}
loopback2={{LoopBackIp2}}
loopback3={{LoopBackIp3}}
loopback4={{LoopBackIp4}}
loopback5={{LoopBackIp5}}
loopback6={{LoopBackIp6}}